### PR TITLE
v3.103: added variable font

### PR DESCRIPTION
**Pull request by m4rc1e**
@davelab6 please merge @alexeiva prs first.

### CODE REVIEW

**Comment by davelab6** [comment]
Merge conflicts

**Comment by m4rc1e** [comment]
I'll rebase this tomorrow.

**Comment by m4rc1e** [comment]
Merge conflict solved.

Avar is fine as well.

screen shot 2018-06-08 at 09 12 08

**Comment by m4rc1e** [comment]
ping @davelab6

**Comment by m4rc1e** [comment]
@davelab6 I've just updated this project.

We now have an unhinted VF which works in Word and the start of a VTT hinted font. I'd like @laerm0 to finish off the vtt hinting. I've inserted deltas but we need to do further manual tweaks.

Lets merge this so we can continue

**Comment by davelab6** [comment]
Should I merge it?

**Comment by m4rc1e** [comment]
Perhaps it would be better for Micah to pull this pr then repush once he's finished the hinting? that would be the cleanest approach.

**Comment by laerm0** [comment]
I can do that. 👍

**Comment by m4rc1e** [comment]
@laerm0 Sorry to disturb, some accents are colliding with base glyphs. I don't exactly know at which sizes this occurs. Mind inserting some instructions to stop this from happening?

desktop_windows_10_chrome_69 0_
_Win 10 Chrome 67 view full size_

Please repull this pr and work on the new fonts.

**Comment by m4rc1e** [comment]
@laerm0 It seems to be happening more in the Bold than the other instances.

**Comment by laerm0** [comment]
...although I did have some ideas on improving the functions for VF. How about we push this now and I'll work on that later this year? Thoughts @davelab6 ?

**Comment by m4rc1e** [comment]
My latest approach uses the wip ttfautohint and I include a Regular master. Imo this approach is producing the best results:

desktop_windows_10_chrome_69 0_
_All glyphs at 13pt (same as previous image) using ttfautohintVF with Reg Master included_

@davelab6 I'm attaching both both sets of diffs. I've updated the pr to include the ttf autohint version. If you prefer the vtt, I can revert back.

**Comfortaa hinted with vtt**
[Comfortaavtt.zip](https://github.com/googlefonts/comfortaa/files/2542896/Comfortaavtt.zip)


**Comfortaa with ttfa and Reg master**
[Comfortaattfa.zip](https://github.com/googlefonts/comfortaa/files/2542898/Comfortaattfa.zip)

If we're all happy to proceed with this approach, I'll hand over all my tools to Micah (B stack account) and run through the workflow. Admittedly this isn't as simple as just running the fonts through ttfautohintVF, there are a few things which could impact the quality.

---
After studying ttfautohintVF, I discovered it will produce a cvar table. This table stores the cvt values for each master in the font. fonttools varLib mutator can mutate this table so each static instance will have reliable cvts.

Since vtt complicates the workflow, I suggest we use ttfautohintVF and improve it. I also suggest @laerm0 becomes the render king. He's not just responsible for vtt hinting, but ensuring that we push fonts which cause no hinting regressions.

**Comment by laerm0** [comment]
Looks very good! Any idea why Cyrillic heights are bouncing?

**Comment by m4rc1e** [comment]
I know the scale of those scripts wasn't intentional but the cap height now matches the Latin. If we look at the Cyrillic, we can see that some letterforms are using the Latin glyphs as components.

**Before**
screen shot 2018-11-09 at 14 59 57
_Cyrillic glyphs not matching cap height of Latin_

**After**
screen shot 2018-11-09 at 15 02 06
_Cyrillic glyphs now have same cap height as Latin_

I would like us to use this version instead of the vtt version because we'll then have three families which use different hinting approaches. We have the following:

ComfortaaVF: ttfautohintVF
DosisVF: vtt
Kreon: No hinting, just prep table fix

**Comment by m4rc1e** [comment]
@davelab6 lets merge this so I can send a pr to google/fonts for sandboxing.

**Comment by davelab6** [comment]
Done

Agree the 3 approaches are nice

**Pull request merged**
